zookeeper:
  container_name: zookeeper
  image: bochen/zookeeper:3.5.1-alpha
  ports:
    - "2181:2181"
    - "2888:2888"
    - "3888:3888"
    - "9696:9696"
  environment:
    ZK_XMS: 128m
    ZK_XMX: 512m

scalable-zookeeper:
  image: bochen/zookeeper:3.5.1-alpha
  ports:
    - "2181"
    - "2888"
    - "3888"
    - "9696"
  environment:
    ZK_XMS: 128m
    ZK_XMX: 512m
    ZK_ENABLE_CLUSTER: 1
  links:
    - zookeeper:zk

kafka:
  container_name: kafka
  image: bochen/kafka:0.9.0.1
  ports:
    - "9092:9092"
    - "9898:9898"
  environment:
    KAFKA_XMS: 256m
    KAFKA_XMX: 512m
    KAFKA_LOG_RETENTION_HOURS: 1
    KAFKA_LOG_RETENTION_BYTES: 314572800
  links:
    - zookeeper:zk

scalable-kafka:
  image: bochen/kafka:0.9.0.1
  ports:
    - "9092"
    - "9898"
  environment:
    KAFKA_XMS: 256m
    KAFKA_XMX: 512m
    KAFKA_LOG_RETENTION_HOURS: 1
    KAFKA_LOG_RETENTION_BYTES: 314572800
  links:
    - zookeeper:zk
